version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  gitea:
    image: "gitea/gitea:latest"
    container_name: "gitea"
    volumes:
      - ./gitea:/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.louiszgm.xin`)"
      - "traefik.http.routers.gitea.entrypoints=web"

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./mysql:/var/lib/mysql
