version: '2'
services:
  jenkins-server:
    image: jenkins/jenkins
    container_name: jenkins
    networks:
      - nginx_outside
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      - ./timezone:/etc/timezone
networks:
  nginx_outside:
    external: true
